#undef SDLRAII_PUT_PREFIX
#undef SDLRAII_GENSYM_
#undef SDLRAII_DEFUNIQUE_WITH_SYM_
#undef SDLRAII_DEFUNIQUE
#undef SDLRAII_WRAP_TYPE
#undef SDLRAII_WRAP_RAIIFN
#undef SDLRAII_WRAP_CREATE_THROW_IF_NULL
#undef SDLRAII_WRAP_FN
